'use client';
import { create } from 'zustand';
import { get, set } from 'idb-keyval';
import type { DemoWorkspace, DeviceMode, DrawerHeight, DrawerTab, TerminalLine, VisionTelemetry } from '@/types/workspace';
const appFile=(title:string,body:string)=>`export default function Page(){return <main className="min-h-screen bg-slate-950 p-8 text-slate-100"><section className="rounded-3xl border border-white/10 bg-slate-900/80 p-8 shadow-2xl"><p className="text-sm uppercase tracking-[.3em] text-indigo-300">SnapDeploy demo</p><h1 className="mt-3 text-4xl font-black">${title}</h1><div className="mt-6 grid gap-4 md:grid-cols-3">${body}</div></section></main>}`;
export const demoWorkspaces: DemoWorkspace[]=[
{id:'fintech',name:'FinTech SaaS Metrics',description:'Revenue velocity, invoices, JWT middleware, Prisma schema.',accent:'#10b981',templateTags:['Stripe','JWT','Prisma','Charts'],openApiSpec:'openapi: 3.1.0\ninfo:\n  title: FinTech Billing API\n  version: 1.0.0\npaths:\n  /api/invoices:\n    get:\n      responses:\n        "200": { description: Invoice list }',diagnostics:['Vision: detected KPI cards and invoice table','Auth middleware synthesized','Prisma SQLite schema validated'],files:{'package.json':'{"scripts":{"dev":"next dev"},"dependencies":{"next":"latest","react":"latest","react-dom":"latest"}}','src/app/page.tsx':appFile('FinTech SaaS Metrics & Invoicing Dashboard',['MRR $128.4k','Churn 1.8%','Invoices 342'].map(x=>`<article className="rounded-2xl bg-emerald-500/10 p-5"><b>${x}</b><p className="mt-2 text-sm text-slate-300">Live metric with revenue velocity trend.</p></article>`).join('')),'prisma/schema.prisma':'datasource db { provider = "sqlite" url = "file:./dev.db" }\nmodel Invoice { id String @id amount Int status String }','middleware.ts':'export function middleware(){ return Response.next(); }'}},
{id:'agents',name:'AI Multi-Agent Canvas',description:'Planner/Coder/Reviewer DAG with streaming route handlers.',accent:'#6366f1',templateTags:['DAG','Streaming','Agents'],openApiSpec:'openapi: 3.1.0\ninfo:\n  title: Agent Workflow API\n  version: 1.0.0\npaths:\n  /api/stream:\n    post:\n      responses:\n        "200": { description: Token stream }',diagnostics:['Diagram nodes mapped to DAG','Cycle detector passed','Streaming handler generated'],files:{'src/app/page.tsx':appFile('AI Multi-Agent Workflow Canvas',['Planner','Coder','Reviewer'].map((x,i)=>`<article className="rounded-2xl border border-indigo-400/30 p-5"><b>${i+1}. ${x}</b><p className="mt-2 text-sm text-slate-300">Connected pipeline node with streamed state.</p></article>`).join('')),'src/app/api/stream/route.ts':'export async function POST(){ return new Response("planner\\ncoder\\nreviewer", { headers: { "content-type": "text/plain" } }); }'}},
{id:'commerce',name:'E-Commerce Micro-Storefront',description:'Optimistic cart, filters, checkout validation, OpenAPI spec.',accent:'#f59e0b',templateTags:['Cart','Checkout','OpenAPI'],openApiSpec:'openapi: 3.1.0\ninfo:\n  title: Storefront API\n  version: 1.0.0\npaths:\n  /api/products:\n    get:\n      responses:\n        "200": { description: Products }',diagnostics:['Wireframe shelves detected','Cart state optimized','Checkout schema emitted'],files:{'src/app/page.tsx':appFile('E-Commerce Micro-Storefront',['Keyboard $129','Headphones $89','Dock $179'].map(x=>`<article className="rounded-2xl bg-amber-500/10 p-5"><b>${x}</b><button className="mt-4 rounded-full bg-amber-400 px-4 py-2 text-slate-950">Add optimistically</button></article>`).join('')),'src/lib/checkout.ts':'export const validateCheckout = (email: string) => /.+@.+/.test(email);'}}];
interface WorkspaceState { workspaces: DemoWorkspace[]; activeId:string; activeFile:string; files:Record<string,string>; drawerTab:DrawerTab; drawerHeight:DrawerHeight; device:DeviceMode; autoFix:boolean; terminal:TerminalLine[]; telemetry:VisionTelemetry[]; hydrated:boolean; setActive:(id:string)=>void; updateFile:(p:string,c:string)=>void; setActiveFile:(p:string)=>void; setDrawer:(t:DrawerTab,h?:DrawerHeight)=>void; setDevice:(d:DeviceMode)=>void; toggleAutoFix:()=>void; addTerminal:(l:TerminalLine)=>void; hydrate:()=>Promise<void> }
const initial=demoWorkspaces[0]!;
export const useWorkspaceStore=create<WorkspaceState>((setState,getState)=>({workspaces:demoWorkspaces,activeId:initial.id,activeFile:'src/app/page.tsx',files:initial.files,drawerTab:'terminal',drawerHeight:'default',device:'desktop',autoFix:true,terminal:[{id:'0',stream:'system',text:'SnapDeploy AI sandbox initialized.',timestamp:Date.now()}],telemetry:[{label:'Layout regions',confidence:.94,detail:'Navbar, sidebar, editor, preview and drawer separated.'},{label:'Backend intent',confidence:.88,detail:'API resources inferred from diagram annotations.'}],hydrated:false,setActive:(id)=>{const ws=getState().workspaces.find(w=>w.id===id); if(ws) setState({activeId:id,files:ws.files,activeFile:Object.keys(ws.files)[0]??'src/app/page.tsx'});},updateFile:(p,c)=>setState(s=>({files:{...s.files,[p]:c}})),setActiveFile:(p)=>setState({activeFile:p}),setDrawer:(drawerTab,drawerHeight)=>setState(s=>({drawerTab,drawerHeight:drawerHeight??s.drawerHeight})),setDevice:(device)=>setState({device}),toggleAutoFix:()=>setState(s=>({autoFix:!s.autoFix})),addTerminal:(l)=>setState(s=>({terminal:[...s.terminal,l].slice(-300)})),hydrate:async()=>{const saved=await get<Partial<WorkspaceState>>('snapdeploy-workspace').catch(()=>undefined); if(saved) setState(saved); setState({hydrated:true});}}));
useWorkspaceStore.subscribe((s)=>{ void set('snapdeploy-workspace',{activeId:s.activeId,activeFile:s.activeFile,files:s.files,drawerTab:s.drawerTab,drawerHeight:s.drawerHeight,device:s.device,autoFix:s.autoFix}); if(typeof localStorage!=='undefined') localStorage.setItem('snapdeploy-workspace',JSON.stringify({activeId:s.activeId})); });
